AWSTemplateFormatVersion: 2010-09-09
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "EC2 Instance Config"
        Parameters:
          - GoldImgID
          - ClusterInstanceType
      - 
        Label: 
          default: "Cluster Config"
        Parameters:
          - EC2ClusterClusterName
          - EC2ClusterVPC
          - EC2ClusterSubnets
          - EC2KeyPair
          - EC2ClusterSecurityGroup
      - 
        Label: 
          default: "NLB and Autoscaling Config"
        Parameters:
          - HealthcheckPort
          - NLBExposePort
          - NLBSubnets
          - NLBScheme
          - ClusterAutoScallingCPUThreshold
          - ClusterDefaultInstanceCount
          - MinimalInstanceCount
          - ClusterMaximumInstanceCount      
Resources:
  EC2ClusterAutoScalingGroupConfiguration:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Properties:
      KeyName: !Ref EC2KeyPair
      ImageId: !Ref GoldImgID # 创建的EC2基础镜像AMI ID
      SecurityGroups:
        - !Ref EC2ClusterSecurityGroup
      InstanceType: !Ref ClusterInstanceType

  EC2ClusterAutoScalingPolicyCPUUtilization:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref EC2ClusterAutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: !Ref ClusterAutoScallingCPUThreshold

  EC2ClusterTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 10
      VpcId: !Ref EC2ClusterVPC
      Protocol: TCP
      Port: !Ref HealthcheckPort

  EC2ClusterNLB:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Name: !Ref EC2ClusterClusterName
      Type: network
      Scheme: !Ref NLBScheme
      Subnets: !Split [',', !Join [',', !Ref NLBSubnets]]

  EC2ClusterELBListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    DependsOn:
      - EC2ClusterNLB
      - EC2ClusterTargetGroup
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref EC2ClusterTargetGroup
      Port: 80
      Protocol: TCP
      LoadBalancerArn: !Ref EC2ClusterNLB

  EC2ClusterAutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    DependsOn:
      - EC2ClusterAutoScalingGroupConfiguration
      - EC2ClusterTargetGroup
    Properties:
      TargetGroupARNs:
        - !Ref EC2ClusterTargetGroup
      VPCZoneIdentifier: !Split [',', !Join [',', !Ref EC2ClusterSubnets]]
      DesiredCapacity: !Ref ClusterDefaultInstanceCount
      HealthCheckGracePeriod: 100
      LaunchConfigurationName: !Ref EC2ClusterAutoScalingGroupConfiguration
      MinSize: !Ref MinimalInstanceCount
      MaxSize: !Ref ClusterMaximumInstanceCount
      Tags:
        - Key: Name
          Value: !Ref EC2ClusterClusterName
          PropagateAtLaunch: true
Parameters:
  GoldImgID:
    Type: 'AWS::EC2::Image::Id'
    Description: Gold ImageID
  HealthcheckPort:
    Type: Number
    Description: Target HealthcheckPort
    Default: 80
  NLBExposePort:
    Type: Number
    Description: NLB Expose HealthcheckPort
    Default: 80
  NLBSubnets:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: Choose one or more valid subnet for NLB
  NLBScheme:
    Type: String
    Default: internet-facing
    AllowedValues:
      - internet-facing
      - internal
    Description: Internal or internet-facing Network Loadbalance
  ClusterAutoScallingCPUThreshold:
    Type: Number
    Description: Set CPU threshold for Cluster cluster scale up
    Default: 60
  ClusterDefaultInstanceCount:
    Type: Number
    Description: Set initial size of EC2 instances for Cluster
    Default: 2
  MinimalInstanceCount:
    Type: Number
    Description: Set minimize size of EC2 instances for Cluster
    Default: 0
  ClusterMaximumInstanceCount:
    Type: Number
    Description: Set maximum size of EC2 instances for Cluster
    Default: 4
  ClusterInstanceType:
    Type: String
    Default: t3.micro
    AllowedValues:
      - c6i.4xlarge
      - c6i.2xlarge
      - c6i.xlarge
      - c6i.large
      - t3.micro
    Description: Enter EC2 type for cluster.
  EC2ClusterClusterName:
    Type: String
    Description: Specific Cluster Name
  EC2ClusterVPC:
    Type: 'AWS::EC2::VPC::Id'
    Description: Choose one valid VPC for Cluster
  EC2ClusterSubnets:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: Choose one or more valid subnet for Cluster
  EC2KeyPair:
    Type: 'AWS::EC2::KeyPair::KeyName'
    Description: Select the key pair for those EC2 instance
  EC2ClusterSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup::Id'
    Description: Choose Security Group for this cloudformation
Outputs:
  EC2ClusterNLBDNSName:
    Description: The DNSName of the Cluster NLB load balancer
    Value: !GetAtt EC2ClusterNLB.DNSName